version: '3.4'
services:
  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  db-data:
