spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

camunda.bpm:
  admin-user:
    id: admin
    password: admin
    email: eventobservability@gmail.com
    firstName: Camunda
    lastName: Admin
  filter:
    create: All tasks
  database:
    type: postgres